---
title: "twitter"
author: "Dar Nettler & Carmela Davidovsky"
date: "December 18, 2017"
output: html_document
---

```{r}
install.packages("twitteR")
install.packages("httr")
install.packages("base64enc")
install.packages("jsonlite")
install.packages("wordcloud")
install.packages("tm")
install.packages("stringr")
install.packages("igraph")
install.packages("digest")
install.packages("rgl")
```

Loading relevant packages: 
```{r}
library(twitteR)
library(httr)
library(jsonlite)
library(tm)
library(stringr)
library(igraph)
library(digest)
library(rgl)

```

```{r}
# start the authorisation process
myapp = oauth_app("twitter", key="h055FoysHKU57ryKbIZvMVwaC", secret="7gbAzHv5dmeaVhOusLqQw9lm7MV8CznrUBZRd0fT0qw4UVbZbL")

# sign using token and token secret
sig1 = sign_oauth1.0(myapp, token="2268807271-b0r3vOtx98FzXBSSXP4xSTcP0muQPkHE7j7JWFQ", token_secret="djF1urmuH1xQ7BUcOIXvcHEZzGyWQiuxxgdX9aKPWgCrp")
```

```{r}
sig <- setup_twitter_oauth("h055FoysHKU57ryKbIZvMVwaC", "7gbAzHv5dmeaVhOusLqQw9lm7MV8CznrUBZRd0fT0qw4UVbZbL", "2268807271-b0r3vOtx98FzXBSSXP4xSTcP0muQPkHE7j7JWFQ", "djF1urmuH1xQ7BUcOIXvcHEZzGyWQiuxxgdX9aKPWgCrp")
```
```{r}


res<-searchTwitter("#GreysAnatomy",n=1500, lang = "en")
#res<-res2
temp<-list()
hashtags<-c()
left<-c()
right<-c()
not<-c("#GreysAnatomy")

#go over each tweet
for(i in 1:1500){
  #extract all of the tweet's hashtags
  w<-res[[i]]$text
  temp[i]<-str_extract_all(w,"#\\S+")
  #add the hashtags to a vector, not including "#GreysAnatomy"
  for(j in 1:length(temp[[i]])){
        hashtags<-c(hashtags,temp[[i]][j])
        hashtags<-hashtags[!hashtags %in% not]
  }
  #create the egdes of the graph
  if(length(hashtags)!=0){
  for(j in 1:length(hashtags))
    for(k in 1:length(hashtags))
        if(j<k){
          left<-c(left,hashtags[j])
          right<-c(right,hashtags[k])
        }
  }
  #reset vector for next tweet
  hashtags<-c()
}

#create data fram
df<-data.frame(left,right)
df<-df[!duplicated(df),]
write.csv(df,file="1500.csv",row.names = FALSE)
    
```

```{r}
# df<-data.frame(left,right)
# df<-df[!duplicated(df),]
# write.csv(df,file="2000.csv",row.names = FALSE)
readddd<-read.csv("1500.csv",header=T)
graphy<-graph.data.frame(readddd,directed = F)
#E(graphy)<-E(graphy) %>% unique()
V(graphy)$name
#degree(graphy)
V(graphy)$size<-degree(graphy)
V(graphy)$label<-NA
plot(graphy, margin=-0.1)
#tkplot(graphy,layout=layout.kamada.kawai)

```

```{r}

```